config/routes.rb
Rails.application.routes.draw do
  root to: 'home#show'

  resources :photos, only: [:index]
  resources :products, only: [:index]
  resources :comments, only: [:index, :create]
end

app/models/comment.rb
class Comment < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def index
    @comments = Comment.all
    respond_to do |format|
      format.html
      format.json {render json: @comments}
    end
  end

  def create
    Comment.create!(params.permit(:author, :text))

    render json: Comment.all
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def show; end
end

app/controllers/photos_controller.rb
class PhotosController < ApplicationController
  def index
    @images = [
      {
        imageUrl: 'http://tinyurl.com/lkevsb9',
        caption: 'New York!'
      },
      {
        imageUrl: 'http://tinyurl.com/mxkwh56',
        caption: 'Cows'
      },
      {
        imageUrl: 'http://tinyurl.com/nc7jv28',
        caption: 'Scooters'
      }
    ]
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  def index
    @products = [
      {category: "Sporting Goods", price: "$49.99", stocked: true, name: "Football"},
      {category: "Sporting Goods", price: "$9.99", stocked: true, name: "Baseball"},
      {category: "Sporting Goods", price: "$29.99", stocked: false, name: "Basketball"},
      {category: "Electronics", price: "$99.99", stocked: true, name: "iPod Touch"},
      {category: "Electronics", price: "$399.99", stocked: false, name: "iPhone 5"},
      {category: "Electronics", price: "$199.99", stocked: true, name: "Nexus 7"}
    ];
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/comments/index.html.erb
<%= react_component('CommentBox', {url: comments_path(format: :json), pollInterval: 2000}, {prerender: false}) %>

app/views/home/show.html.erb
<ul>
  <li><%= link_to "Photos", photos_path %></li>
  <li><%= link_to "Products", products_path %></li>
  <li><%= link_to "Comments", comments_path %></li>
</ul>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>React+Rails Demo</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <div class="navbar navbar-inverse">
    <div class="navbar-header">
      <a class="navbar-brand" href="<%= root_path %>">React+Rails</a>
    </div>
    </div>
  </div>
  <div class="container">
    <%= yield %>
  </div>
</body>
</html>

app/views/photos/index.html.erb
<%= react_component('PhotoGallery', {images: @images}, {prerender: true}) %>

app/views/products/index.html.erb
<%= react_component('Products', {products: @products}, {prerender: true}) %>